#!/usr/bin/env bash

# always check timesyncd.enable=false
# rm iso/airootfs/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service
# rm iso/airootfs/etc/systemd/system/sysinit.target.wants/systemd-time-wait-sync.service
# rm iso/airootfs/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service

set -e

sudo umount -l work/x86_64/airootfs/proc &
sudo umount -l work/x86_64/airootfs/sys &
sudo umount -l work/x86_64/airootfs/dev &
sudo umount -l work/x86_64/airootfs/run &

echo "Cleaning previous build and pacman locks..."
sudo rm -rf work/ out/
sudo rm -f /var/lib/pacman/db.lck
sudo pacman -Syy

echo "Starting mkarchiso build..."
export MKARCHISO_PKG_CACHE=./archiso-cache/pkg
sudo mkarchiso -v -w work -o out .

echo "✅ Build complete! ISO is in 'out/'"

