#!/usr/bin/env bash
set -e

sudo umount -l work/x86_64/airootfs/proc &
sudo umount -l work/x86_64/airootfs/sys &
sudo umount -l work/x86_64/airootfs/dev &
sudo umount -l work/x86_64/airootfs/run &

echo "Cleaning previous build and pacman locks..."
sudo rm -rf work/ out/
sudo rm -f /var/lib/pacman/db.lck
sudo pacman -Syy

echo "Starting mkarchiso build..."
export MKARCHISO_PKG_CACHE=./archiso-cache/pkg
sudo mkarchiso -v -w work -o out .

echo "✅ Build complete! ISO is in 'out/'"

