#!/bin/bash

# __   _____  _   _ _   _ _____  __
# \ \ / / _ \| | | | \ | |_ _\ \/ /
#  \ V / | | | | | |  \| || | \  /
#   | || |_| | |_| | |\  || | /  \
#   |_| \___/ \___/|_| \_|___/_/\_\
#
# Lisence GPL3
# Homepage: https://github.com/apapamarkou/younix
# Author: Andrianos Papamarkou
# Email: papamarkoua@gmail.com

# This script syncs specified files from home directory to the dotfiles directory
# and it is ment to use by the developers of this project

SCRIPT_DIR="$(pwd)"
SKEL_FILE="$SCRIPT_DIR/sync-skel.txt"
SKEL="$SCRIPT_DIR/airootfs/etc/skel"

# copy SKEL files
while IFS= read -r path || [ -n "$path" ]; do
    # Skip blank lines and comments
    [[ -z "${path// }" || "${path:0:1}" == "#" ]] && continue

    SRC="$HOME/$path"

    if [ -e "$SRC" ]; then
        # copy to skel
        echo "Syncing to skel: $SRC -> $SKEL"
        sudo rsync -a --delete --relative "$HOME/./$path" "$SKEL"
    else
        echo "⚠️ Missing: $SRC"
    fi
done < "$SKEL_FILE"

# sync $HOME/.local/bin/* to airootfs/usr/local/bin no subfolders
DEST="$SCRIPT_DIR/airootfs/usr/local/bin"
SOURCE="$HOME/.local/bin"
echo "Syncing to airootfs/usr/local/bin: $SOURCE/* -> $DEST"
sudo rsync -a "$SOURCE/"* "$DEST/"

# sync /etc/environment
echo "Syncing to airootfs/etc/environment: /etc/environment"
sudo rsync -a --delete /etc/environment "$SCRIPT_DIR/airootfs/etc/"

# sync gtk settings
echo "Syncing to airootfs/etc/gtk-3.0: /etc/gtk-3.0"
sudo rsync -a --delete /etc/gtk-3.0 "$SCRIPT_DIR/airootfs/etc/"
sudo rm "$SCRIPT_DIR/airootfs/etc/gtk-3.0/im-multipress.conf"
echo "Syncing to airootfs/etc/gtk-4.0: /etc/gtk-4.0"
sudo rsync -a --delete /etc/gtk-4.0 "$SCRIPT_DIR/airootfs/etc/"

# sync /usr/share/hypr/conf.d/*
echo "Syncing to airootfs/usr/share/hypr/conf.d: /usr/share/hypr/conf.d"
sudo rsync -a --delete /usr/share/hypr/conf.d "$SCRIPT_DIR/airootfs/usr/share/hypr/"

# sync /etc/fish
echo "Syncing to airootfs/etc/fish: /etc/fish"
sudo rsync -a --delete /etc/fish "$SCRIPT_DIR/airootfs/etc/"

# sync /usr/local/share/shell
echo "Syncing to airootfs/usr/local/share/shell: /usr/local/share/shell"
sudo rsync -a --delete /usr/local/share/shell "$SCRIPT_DIR/airootfs/usr/local/share/"

# sync /usr/share/backgrounds
echo "Syncing to airootfs/usr/share/backgrounds: /usr/share/backgrounds"
sudo rsync -a --delete /usr/share/backgrounds "$SCRIPT_DIR/airootfs/usr/share/"

echo "✅ Sync completed."
